{% set version = "5.7.8" %}

package:
  name: notebook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/notebook/notebook-{{ version }}.tar.gz
  sha256: 573e0ae650c5d76b18b6e564ba6d21bf321d00847de1d215b418acb64f056eb8

build:
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
    - find {{ PREFIX }} -name '*.js.map' -delete  # [not win]
  number: 1
  entry_points:
    - jupyter-notebook = notebook.notebookapp:main
    - jupyter-nbextension = notebook.nbextensions:main
    - jupyter-serverextension = notebook.serverextensions:main
    - jupyter-bundlerextension = notebook.bundler.bundlerextensions:main

requirements:
  host:
    - python
    - pip
  run:
    - ipykernel
    - ipython_genutils
    - jinja2
    - jupyter_core >=4.4.0
    - jupyter_client >=5.2.0
    - nbconvert
    - nbformat
    - python
    - pyzmq >=17
    - send2trash
    - terminado >=0.8.1
    - tornado >=4.1,<7
    - traitlets >=4.2.1
    - prometheus_client
    - ipaddress  # [py2k]

test:
  commands:
    - jupyter notebook -h
    - jupyter nbextension -h
    - jupyter serverextension -h
    - jupyter bundlerextension -h
  imports:
    - notebook

about:
  home: http://jupyter.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: A web-based notebook environment for interactive computing

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - gnestor
    - takluyver
