# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 7.5.0a0
  lab_version: ">=4.5.0a0,<4.5"

package:
  name: notebook
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/notebook/notebook-${{ version }}.tar.gz
  sha256: bf26d98588be0d3d0a1d286521a60f7fc2f72f93afe23688fd4790fccbe18e5a

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyter-notebook = notebook.app:main

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatchling >=1.11
    - jupyterlab ${{ lab_version }}
    - pip
    - python ${{ python_min }}.*
  run:
    - importlib_resources >=5.0
    - jupyter_server >=2.4.0,<3
    - jupyterlab ${{ lab_version }}
    - jupyterlab_server >=2.27.1,<3
    - notebook-shim >=0.2,<0.3
    - python >=${{ python_min }}
    - tornado >=6.2.0

tests:
  - python:
      imports: notebook
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pip check
      - jupyter notebook -h
      - jupyter-notebook -h
      - jupyter labextension list --debug
      - >-
        jupyter labextension list --debug 2>&1 
        | python -c "import sys, re; assert re.match(r'@jupyter-notebook/lab-extension.*OK', sys.stdin.read()), 'ext not ok'"

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - notebook/labextension/static/third-party-licenses.json
    - notebook/static/third-party-licenses.json
  summary: A web-based notebook environment for interactive computing
  homepage: https://github.com/jupyter/notebook
  documentation: https://jupyter-notebook.readthedocs.io

extra:
  recipe-maintainers:
    - krassowski
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - gnestor
    - takluyver
    - lresende
    - bollwyvl
    - blink1073
    - davidbrochart
    - jtpio
