appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: N6lpFUWr56bbXFVgbbhbLGJoXYAsYy7QRaaEyAvQd/zpR03LkyYyDCwgQFj38ASIYZhMWg5kJlqwQqPPdjIkBu5SS+F8D5aBo+4AYYAxCg0zONaDBlg1Pe5dXwiM9ZrKtpOMgFT7pfzi7/8iLK1MOwjCdjR1Zlu9zXEqImkbe+6A9Ar0B3OjiFaLCGCsZfaVvLK5QDzMboEsx3kGaOY4ghYxnmVPRN4ZdJc9ceAcnhIWszW5/ibwQD150A67NyQRxQqQLW5ibEV4M0pS3Qs5ERhDxxq7/2leMuExpHjEzqJ4Xon72zKNJW5dh4PPn2u21nqrduW9BXEh7EDSw9iwXZ0ZRXWuaTSI1R3/65aBFdLcroBsFp9zqXTYDxns3OilEQNx2BOHuCGV+uFRXgvfSY3h5V5Uk9xWKBDZLUH8VqEceKtEk6iOcvZlp9Rmbr/CAhGgHmcLjpzB1O2RMuf6uYrEaVS2uZ2R+AZfOAP+yynqT4uYt93UPEP2MxGUZq6qt76Q9vrk4hOmKqhjq1g3xe2BLlJszCXj3gxBKp5BPnI+2LsX3TtiaYAgBzBnDS/5Q2mLwjhz5VLdpmvORs7qyRhsV2NPLqpRYkWjCLDPF2tptKUK9REjOp3gd3QIDMV/Qv4h6r0WGi6p2/iQGNTHGgB8Mt4y4bx016XSNtT6iV0=}
